/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.admin.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author dell
 */
@Template(FormPage.class)
public class UserPage extends javax.swing.JPanel {

    /**
     * Creates new form UserPage
     */
    public UserPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xTabbedPane1 = new com.rameses.rcp.control.XTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xSubFormPanel1 = new com.rameses.rcp.control.XSubFormPanel();
        jPanel1 = new javax.swing.JPanel();
        photoComponent1 = new com.rameses.enterprise.components.PhotoComponent();

        setPreferredSize(new java.awt.Dimension(656, 512));
        setLayout(new java.awt.BorderLayout());

        xTabbedPane1.setPreferredSize(new java.awt.Dimension(656, 512));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 10, 10, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        xFormPanel1.setCaptionWidth(100);

        xTextField1.setCaption("Username");
        xTextField1.setEnabled(false);
        xTextField1.setName("entity.username"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(200, 20));
        xTextField1.setRequired(true);
        xTextField1.setSpaceChar('_');
        xFormPanel1.add(xTextField1);

        xTextField3.setCaption("Last Name");
        xTextField3.setEnabled(false);
        xTextField3.setName("entity.lastname"); // NOI18N
        xTextField3.setPreferredSize(new java.awt.Dimension(200, 20));
        xTextField3.setRequired(true);
        xFormPanel1.add(xTextField3);

        xTextField2.setCaption("First Name");
        xTextField2.setEnabled(false);
        xTextField2.setName("entity.firstname"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(200, 20));
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xTextField5.setCaption("Middle Name");
        xTextField5.setEnabled(false);
        xTextField5.setName("entity.middlename"); // NOI18N
        xTextField5.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel1.add(xTextField5);

        xTextField6.setCaption("Job Title");
        xTextField6.setEnabled(false);
        xTextField6.setName("entity.jobtitle"); // NOI18N
        xTextField6.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel1.add(xTextField6);

        xTextField4.setCaption("User Txn Code");
        xTextField4.setEnabled(false);
        xTextField4.setName("entity.txncode"); // NOI18N
        xTextField4.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel1.add(xTextField4);

        jPanel2.add(xFormPanel1, java.awt.BorderLayout.NORTH);

        xTabbedPane1.addTab("  General Info     ", jPanel2);

        xPanel1.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(0, 40));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel8.setLayout(flowLayout1);

        jLabel3.setText("Select Domain");
        jPanel8.add(jLabel3);

        xComboBox1.setItems("xdomainList");
        xComboBox1.setName("xdomain"); // NOI18N
        xComboBox1.setAllowNull(false);
        xComboBox1.setPreferredSize(new java.awt.Dimension(250, 40));
        jPanel8.add(xComboBox1);

        xPanel1.add(jPanel8, java.awt.BorderLayout.NORTH);

        xSubFormPanel1.setDepends(new String[] {"xdomain"});
        xSubFormPanel1.setHandler("roleHandler");
        xSubFormPanel1.setDynamic(true);
        xPanel1.add(xSubFormPanel1, java.awt.BorderLayout.CENTER);

        xTabbedPane1.addTab("Roles and Permissions", xPanel1);

        jPanel1.setLayout(new com.rameses.rcp.control.layout.CenterLayout());

        photoComponent1.setName("entity.photo"); // NOI18N
        jPanel1.add(photoComponent1);

        xTabbedPane1.addTab("  Photo     ", jPanel1);

        add(xTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private com.rameses.enterprise.components.PhotoComponent photoComponent1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XSubFormPanel xSubFormPanel1;
    private com.rameses.rcp.control.XTabbedPane xTabbedPane1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    // End of variables declaration//GEN-END:variables
}
