/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.admin.views;

/**
 *
 * @author elmonazareno
 */
public class UserGroupMgmtPage extends javax.swing.JPanel {

    /**
     * Creates new form UserGroupMgmtPage
     */
    public UserGroupMgmtPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        jLabel3 = new javax.swing.JLabel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xSubFormPanel1 = new com.rameses.rcp.control.XSubFormPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(0, 40));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel8.setLayout(flowLayout1);

        xButton1.setName("_close"); // NOI18N
        xButton1.setIconResource("images/toolbar.close.png");
        xButton1.setText("Close");
        jPanel8.add(xButton1);

        jLabel3.setText("Select Domain");
        jPanel8.add(jLabel3);

        xComboBox1.setItems("domainList");
        xComboBox1.setName("domain"); // NOI18N
        xComboBox1.setAllowNull(false);
        xComboBox1.setPreferredSize(new java.awt.Dimension(250, 40));
        jPanel8.add(xComboBox1);

        add(jPanel8, java.awt.BorderLayout.NORTH);

        xSubFormPanel1.setDepends(new String[] {"domain"});
        xSubFormPanel1.setHandler("roleHandler");
        xSubFormPanel1.setDynamic(true);
        add(xSubFormPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel8;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XSubFormPanel xSubFormPanel1;
    // End of variables declaration//GEN-END:variables
}
